replicaCount: 2
metadata:
  name: bank-management
  service: bank-management-service
  namespace: stage
selector:
  name: bank-management
image:
  repository: mlustig/bank-management
  tag: latest
service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080
  nodePort: 30080
db:
  name: postgres
  credentials:
    secretName: postgres-credentials
    usernameKey: username
    passwordKey: password

imagePullSecrets:
  name: dockerhub-secret

nameOverride: ""
fullnameOverride: ""



selectorLabels:
  app: bank-management

environment:
  SPRING_PROFILES_ACTIVE: stage
  SPRING_DATASOURCE_URL: db-config
  SPRING_DATASOURCE_USERNAME: postgres-credentials
  SPRING_DATASOURCE_PASSWORD: postgres-credentials

configMap:
  name: db-config
  key: spring_datasource_url

secret:
  name: postgres-credentials
  username:
    key: username
  password:
    key: password