global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  # Update to 'prometheus' as the target
  - job_name: 'bank-management'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['bank-management:8080']  # Update to 'bank-management' as the target
        labels:
          application: 'Bank Management Application'