apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-management
  template:
    metadata:
      labels:
        app: bank-management
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: bank-management
        image: mlustig/bank-management:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: stage
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: spring_datasource_url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password

---
apiVersion: v1
kind: Service
metadata:
  name: bank-management
  namespace: stage
spec:
  selector:
    app: bank-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080