apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: stage
data:
  spring_datasource_url: "jdbc:postgresql://postgres-service:5432/postgres"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: stage
data:
  grafana.ini: |
    [server]
    http_port = 3000
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
    [paths]
    data = /var/lib/grafana/data
    [analytics]
    check_for_updates = true
    [security]
    admin_user = admin
    admin_password = admin
    [auth.anonymous]
    enabled = true
    org_role = Viewer
    [auth.basic]
    enabled = false
    [auth.google]
    enabled = false
    [log]
    mode = file
    [users]
    allow_sign_up = false

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: stage
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: [ 'prometheus-service:9090' ]
      - job_name: 'bank-management'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: [ 'bank-management-service:8080' ]
            labels:
              application: 'Bank Management Application'
