name: Main CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: |
          gradle build --exclude-task test

  tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install Docker Compose
        run: |
          sudo apt-get update && sudo apt-get install -y docker-compose
      - name: Start Docker Compose
        run: |
          docker-compose up -d
      - name: Build with Gradle
        run: |
          gradle test
      - name: Stop Docker Compose
        run: |
          docker-compose down

  docker:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: |
          gradle build --exclude-task test
      - name: Docker login
        run: |
          docker login -u ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Get Gradle project version
        id: get_version
        run: |
            echo "VERSION=$(sed -nE 's/version=([0-9]+\.[0-9]+\.[0-9]+)/\1/p' gradle.properties)" >> $GITHUB_ENV
      - name: Docker build and tag
        run: |
          docker build -t mlustig/bank-management:${{ env.VERSION }} --build-arg VERSION=${{ env.VERSION }} .
          docker push mlustig/bank-management:${{ env.VERSION }}
          docker tag mlustig/bank-management:${{ env.VERSION }} mlustig/bank-management:latest
          docker push mlustig/bank-management:latest

  update-version:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Create New Branch
        run: |
          git config --global user.name "Meir Lustig"
          git config --global user.email "meirlustig1983@gmail.com"
          git fetch origin main
          git branch -D update-gradle-properties || true
          git checkout -b update-gradle-properties --track origin/main
      - name: Update Version
        run: ./gradlew increaseVersion
      - name: Commit and push changes
        run: |
          git config --global credential.helper store
          git add gradle.properties
          git commit -m "Update gradle.properties"
          git pull origin main
          git push --force origin update-gradle-properties
