name: Main CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: |
          gradle build --exclude-task test

  tests:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install Docker Compose
        run: |
          sudo apt-get update && sudo apt-get install -y docker-compose
      - name: Start Docker Compose
        run: |
          docker-compose up -d
      - name: Build with Gradle
        run: |
          gradle test
      - name: Stop Docker Compose
        run: |
          docker-compose down

  docker:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: |
          gradle build --exclude-task test
      - name: Docker login
        run: |
          docker login -u ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Docker build and tag
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          docker build -t mlustig/bank-management:${VERSION} --build-arg VERSION=${VERSION} .
          docker push mlustig/bank-management:${VERSION}
          docker tag mlustig/bank-management:${VERSION} mlustig/bank-management:latest
          docker push mlustig/bank-management:latest
