name: Java CI with Gradle

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose
      - name: Start Docker Compose
        run: docker-compose up -d
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: increaseVersion build
      - name: Commit and push changes
        run: |
          git config --global user.name "Meir Lustig"
          git config --global user.email "meirlustig1983@gmail.com"
          git checkout -b update-gradle-properties
          git add gradle.properties
          git commit -m "Update gradle.properties"
          git push origin update-gradle-properties
      - name: Create a pull request
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            branch: main
            title: BM-Update version properties file with the changes in gradle.properties file
            body: |
              This pull request updates the version properties file based on the changes made in the gradle.properties file.
      - name: Merge the pull request to main
        uses: actions/github-script@v4
        with:
          script: |
            const pullRequest = context.payload.pull_request;
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            octokit.pulls.merge({
              owner: pullRequest.base.user.login,
              repo: pullRequest.base.repo.name,
              pull_number: pullRequest.number,
              merge_method: 'squash'
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Stop Docker Compose
        run: docker-compose down
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Get Gradle project version
        id: get_version
        run: echo "::set-output name=version::$(sed -nE "s/version = '([0-9]+\.[0-9]+\.[0-9]+)'/\1/p" build.gradle)"
      - name: Docker build and tag
        run: |
          docker build -t mlustig/bank-management:${{ steps.get_version.outputs.version }} --build-arg VERSION=${{ steps.get_version.outputs.version }} .
          docker push mlustig/bank-management:${{ steps.get_version.outputs.version }}
          docker tag mlustig/bank-management:${{ steps.get_version.outputs.version }} mlustig/bank-management:latest
          docker push mlustig/bank-management:latest
