name: PR Labeling

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label_documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for README.md changes
        id: check_readme_changes
        run: |
          if git diff-tree --no-commit-id --name-only -r <base_commit>..<head_commit> | grep -qE '^README.md$'; then
            echo "::set-output name=has_readme_changes::true"
          else
            echo "::set-output name=has_readme_changes::false"
          fi
      - name: Label PR with 'documentation'
        if: ${{ steps.check_readme_changes.outputs.has_readme_changes == 'true' }}
        uses: actions/github-script@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context } = github;
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
          
            const labels = ['documentation'];
          
            github.issues.addLabels({
              owner: owner,
              repo: repo,
              issue_number: issueNumber,
              labels: labels
            });
